### ISSUE TITLE
New Table Options

### ISSUE THREAD

**Issue by shammond42** [practicingruby/prawn-layout#11]
Added some new table options. See shammond42/prawn-layout (http://github.com/shammond42/prawn-layout) for implementation. The following options have been implemented.
- :column_color => shade a column of table cells
- rows border style
- outline border style

Also fixed a couple of border rendering bugs that became apparent with the above border styles.

**Comment by practicingruby** [comment]
There is a lot of stuff here.   Can we get this split out into separate tickets so we can discuss them individually?  I think that maybe a patch we merged will fix the border rendering issues, so be sure to re-base against those changes.  If not, definitely interested in bug reports on the issues you ran into.

But I really need to see these features split out into individual tickets which indicate which commits I should merge.  We're too close to 0.6 release to risk bulk merging these changes now, but I'll be happy to review for 0.7 once you've got these sorted out.
