### ISSUE TITLE
The row_colors option causes black boxes on pages > 1

### ISSUE THREAD

**Issue by rnhurt** [practicingruby/prawn-layout#13]
When building a table everything looks good on the first page but the content on any additional page is completely black.  Below is some sample code that shows the error.  Comment out the :row_colors option and everything works fine.

```
  table(
    (1..45).map { [ "foo"] },
    :row_colors => ["DBDBDB", "FFFFFF"],
    :position => :center
  )
```

**Comment by rnhurt** [comment]
BTW: This code worked on Prawn 0.5.x and fails in Prawn 0.6.2 (or whatever is the latest version as of this morning).

**Comment by wpiekutowski** [comment]
Seems that it's an issue caused by the recent changes to color.rb. Apparently table color handling doesn't work properly now for some reason. Please provide a simple Ruby script nailing down the problem, and I'll be happy to investigate this.

**Comment by rnhurt** [comment]
Further investigation of the problem has reveled that the PDF being generated looks OK in some readers but not others.  Here are the results of my testing:
- Evince 2.26.1 on Ubuntu 9.04 renders the first page fine but blacks out table headers/text blocks on additional pages
- OS X Preview 5.0.1 renders the whole PDF properly
- FoxIt 3.1.3 on Windows 7 renders the whole PDF properly
- Adobe Reader 9.x on Windows 7 renders the first page correctly and each additional page is completely blank, not even headers or footers
