### ISSUE TITLE
wire up support for vertical alignment in table cells

### ISSUE THREAD

**Issue by practicingruby** [practicingruby/prawn-layout#14]

**Comment by marksim** [comment]
any known way to hack it in now?

**Comment by marcoribi** [comment]
any patches available?

**Comment by henrik** [comment]
You can sort of fake it by adding enough vertical_padding to the cell.

**Comment by practicingruby** [comment]
This is an old ticket on a dead repository.  Please try the new table API in the development builds of Prawn at http://github.com/sandal/prawn.
