### ISSUE TITLE
'footer' is not margin smart

### ISSUE THREAD

**Issue by jf** [practicingruby/prawn-layout#16]
if you start a footer with a top-left x-coordinate of 38 or greater, stuff gets cut off. To illustrate:

<pre>
footer [38, margin_box.bottom] do
    stroke_horizontal_rule
    text "Align right footer", :align => :right
end
</pre>

**Comment by practicingruby** [comment]
You need to use canvas and margin_box for something like this.  Prawn isn't going to magically flow text beyond the margins for you.
