### ISSUE TITLE
Missing header and footer methods in gem 0.7.1

### ISSUE THREAD

**Issue by samlown** [practicingruby/prawn-layout#17]
Git repository is correct, but the code in the 0.7.1 gem for some strange reason does not include the header and footer methods. Using gem from here:

http://gemcutter.org/gems/prawn-layout

Sam.

**Comment by yob** [comment]
From the notice when the 0.7 gem was installed:

  For those coming from Prawn 0.6 or earlier, note that this release has
  some API breaking changes as well as many new features.  **\* You'll want 
  to know about these changes, as we will no longer be supporting
  Prawn 0.6 or any earlier version of Prawn***

  For details on what has changed, see:
    http://wiki.github.com/sandal/prawn/changelog

**Comment by practicingruby** [comment]
I forgot to apply a change to master.  Behavior should now be as described in the changelog.

**Comment by samlown** [comment]
Thanks for uploading the git repo. But that does leave the question, why would you remove the header and footer methods?

Changelog states:

The prawn/layout extension is currently feature frozen pending a major rewrite...

Surely that means "we're leaving it as it is while we work on it", certainly doesn't suggest you'll be removing features! It would be nice to have a heads-up on these types of changes in the documentation too, labelling the methods with "depricated use -somethingelse- instead" would be a big help.

Nonetheless, if its no longer possible to use prawn-format (without hacks), I'll be sticking with 0.6.X for the time being.

**Comment by practicingruby** [comment]
We removed header/footer because it has always been buggy / unintuitive, and there is now a suitable replacement

The feature freeze applies to contributors.   We are not accepting feature patches.  As for what we do to prawn-layout, that's totally up to us.   Go read our release policy:

http://wiki.github.com/sandal/prawn/release-schedule

**Comment by samlown** [comment]
Okay, my bad, I skimmed through the changelog and missed where it says "use Prawn::Document#repeat instead". As I say, it would be nice to have some kind of deprecation notice for widely used methods:

```
def header
  raise "header and footer methods no longer supported, use #repeat instead"
end
```

Thanks.

**Comment by practicingruby** [comment]
We might consider things like that after 1.0, but for now we've been pretty clear that things will be removed without any warning beyond a note in the CHANGELOG between major releases up until then.
