### ISSUE TITLE
fill_color() no more works with table()

### ISSUE THREAD

**Issue by practicingruby** [practicingruby/prawn-layout#18]
Originally reported by eeabed (Abdul-Jabbar Shalabi):

After upgrading to Prawn 0.7.1, I noticed that table() doesn't respect the current color setting by fill_color(), only the first cell will have text color according to it, but subsequent cells will have just black text.

example:

```
fill_color "ff0000"
table [%w[1 2 3],%w[4 5 6],%w[7 8 9]], 
  :position => :center,
  :border_width   => 0,
  :font_size => 40
```

Only the first cell in the above table has red text color, the rest is just black.
Expected: all text should be red.

Maybe it is worth it to add a :text_color option for table() for setting text color, as we have for headers (:header_text_color)

**Comment by practicingruby** [comment]
Yep, this was a silly bug on our end, not an intentional behavior change.
Please try the latest code on stable branch and see if it fixes the problem.   If so, we'll get a maintenance release out within a couple days.

**Comment by eeabed** [comment]
Thank you very much for your awesome work. Works now as expected.

**Comment by practicingruby** [comment]
Okay, will release in the next week or two.
