### ISSUE TITLE
Grid.show doesn't reset stroke color

### ISSUE THREAD

**Issue by huerlisi** [practicingruby/prawn-layout#20]
When using show_all for on a grid, the stroke color isn't reset afterwards. This is an undesired side effect.

Working on a patch, will post when ready.

**Comment by huerlisi** [comment]
Fix has been commited to my prawn-layout branch at huerlisi/prawn-layout@c5a178efd374034ca2c55f298e604be02f4a636c

This fix depends on transactional color support (issue 76) available in my prawn fork at huerlisi/prawn@a582122

Commit contains rspec test.

**Comment by practicingruby** [comment]
Please update so as not to depend on your patch (see my comment there).   Also note that our tests are test/spec, not rspec.   Make sure your code runs under test/spec.

**Comment by practicingruby** [comment]
We need to check the behavior for when stroke_color wasn't explicitly set.  I think there may be a subtle behavior change there, in that pdf.stroke_color = nil will break.   Add a test to see...

**Comment by huerlisi** [comment]
pdf.*_color seems to be '000000' by default.

Added a test to check if it works with this, too. Didn't want to hardcode 000000, but converting to [0.0,0.0,0.0] seemed to be overkill (rounding...). Maybe someday, I'll implement a little test-helper;-)

**Comment by practicingruby** [comment]
Merged.  Thanks.
