### ISSUE TITLE
Text Box inside Bounding Box Inside Grid shrink_to_fit bug

### ISSUE THREAD

**Issue by rolfb** [practicingruby/prawn-layout#22]
:overflow => :shrink_to_fit does not work if the following conditions occur:

A text box has the same width and height as the bounding_box, which has the same width and height as the grid box we are using for positioning.

The latter with grid box size may be irrelevant, but this was my setup when the bug appeared.
Text which overflowed just disappeared.

:shrink_to_fit started working when i decreased the height and width of the text_box to be smaller than the bounding box.

**Comment by practicingruby** [comment]
please write a reduced example that shows the issue you described above.  In the future, always include examples with bug reports, it really helps us verify what the issue you might be running into is.

**Comment by rolfb** [comment]
I made a static copy of the code I was working on (link at bottom)
But it didn't successfully reproduce the error!

The only variation which is not accounted for is the contents of "data", so it might have been a data dependent error, and I'm closing this issue for now since its not reproducable. 

https://gist.github.com/e4c67dd0a092d2962dbb

**Comment by rolfb** [comment]
Unable to close even if Github gives me the choice of "Comment and close". :)

**Comment by practicingruby** [comment]
Thanks for reporting back.  If you do find a minimal reproductive example, feel free to post here and we'll re-open.

**Comment by rolfb** [comment]
Will do that.

Thanks for all your great work and quick replies :)
