### ISSUE TITLE
Patch replacing 'translate!' with 'map_to_absolute'

### ISSUE THREAD

**Issue by cassiomarques** [practicingruby/prawn-layout#24]
Here is the link to a commit where I replace translate! with 'map_to_absolute'. 

The tests and examples seems to pass just fine. 

http://github.com/cassiomarques/prawn-layout/commit/220cda17cda0eb8aca772947f3f2f488ba2e40e8

**Comment by cassiomarques** [comment]
Oh, sorry for the wrong formatting in the above link. At least it works :)

**Comment by practicingruby** [comment]
Well, they run, but the lazy bounding box example shows you that your patch doesn't work. :)

But it was easy to fix.   instead of translate! -> map_to_absolute, you want translate! -> map_to_absolute!  as the former is not destructive.

Pushing a fix now.

**Comment by practicingruby** [comment]
We really wanted map_to_absolute! (Closed by 8bc75c9100d9958267a955e46d57c3beb6c50021)
