### ISSUE TITLE
prawn-layout 0.8.4 fails tests

### ISSUE THREAD

**Issue by graaff** [practicingruby/prawn-layout#26]
When running the specs I get two failures:

  1) Failure:
test_spec {A document's grid    when a grid is defined} 005 [should draw outlines without changing global default colors to grid color](A document's grid   when a grid is defined)
    [./spec/grid_spec.rb:70:in `test_spec {A document's grid    when a grid is defined} 005 [should draw outlines without changing global default colors to grid color]'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in`**send**'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in `run']:
<[0.0, 0.0, 0.0]> expected but was
<nil>.

  2) Failure:
test_spec {A document's grid    when a grid is defined} 006 [should draw outlines without curent color settings](A document's grid  when a grid is defined)
    [./spec/grid_spec.rb:81:in `test_spec {A document's grid    when a grid is defined} 006 [should draw outlines without curent color settings]'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in`**send**'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in `run']:
<[0.8, 1.0, 0.0]> expected but was
<nil>.

30 tests, 45 assertions, 2 failures, 0 errors

I've made sure to run these against prawn-core 0.8.4, but I saw the same failures with prawn-core 0.7.1. Please let me know if more information is needed.

**Comment by practicingruby** [comment]
If you are running from git, please be sure to update your submodules, as this may be a pdf-inspector issue.

**Comment by graaff** [comment]
I'm using the distributed gems for 0.8.4.

**Comment by graaff** [comment]
Aha! I had an old copy of pdf-inspector laying around which I didn't expect to have. Removing it makes this go away. Thanks for the hint!
